### ISSUE TITLE
pyShelly log JSON cloud error

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#133]
Hi,

from time to time I see the following error in the log:

`2020-01-02 17:25:07 WARNING (Cloud) [pyShelly] Error receive JSON from cloud Unauthorized`
`2020-01-02 17:25:07 ERROR (Cloud) [pyShelly] Error update cloud, 'NoneType' object is not subscriptable`

but everything seems to work fine.

Simone

**Comment by chemelli74** [comment]
I just rename a Plug S device in the cloud, and after a few seconds the new name comes to HA.
So definitively the auth key and server name are fine.

But I noticed that the only parameter not changed was "**sensor.shelly_shplg_s_xxxxxx_consumption**" that is still reported with the old name.

Simone

**Comment by CiquattroFPV** [comment]
I have the same error.. have you resolved it?

**Comment by hakana** [comment]
Fixed in 0.1.6.b4

**Comment by chemelli74** [comment]
Hi, unfortunately I still have some issue son 0.1.6b6:

![image](https://user-images.githubusercontent.com/57354320/72517222-43411080-3853-11ea-9e06-f3e08668c833.png)

Simone

**Comment by hakana** [comment]
Can you turn on the debug log on pyShelly. It will generate lots of logs, but there is a message "POST to Shelly Cloud" that will be sent each time it connects to the Cloud. I need to know if connecting to the cloud more than every second.

**Comment by hakana** [comment]
Are you running anything else that using the Shelly cloud_token?

**Comment by chemelli74** [comment]
> Are you running anything else that using the Shelly cloud_token?

Nope, only your great plugin. And the iOS mobile app integrated with Alexa but I don't think it count ;-)

Simone

**Comment by chemelli74** [comment]
> Can you turn on the debug log on pyShelly. It will generate lots of logs, but there is a message "POST to Shelly Cloud" that will be sent each time it connects to the Cloud. I need to know if connecting to the cloud more than every second.

Seems you do a POST for each device, thus a lot more than every second.
Just restarted HA:


```
2020-01-16 12:39:17 DEBUG (Cloud) [pyShelly] POST to Shelly Cloud
2020-01-16 12:39:20 DEBUG (Cloud) [pyShelly] POST to Shelly Cloud

```

Simone

**Comment by hakana** [comment]
As I can see it not more than every 3 seconds? If you got the error about Request limit reached again have a look there and see how it send the POSTs.

**Comment by chemelli74** [comment]
Hi,

here the log, 1 entry in 3 hours:
```
2020-01-16 14:05:01 DEBUG (mDns) [pyShelly] Check add device by host 192.168.xxx.xxx mDns
2020-01-16 14:05:02 DEBUG (Cloud) [pyShelly] Update from cloud
2020-01-16 14:05:02 DEBUG (Cloud) [pyShelly] POST to Shelly Cloud
2020-01-16 14:05:06 DEBUG (Cloud) [pyShelly] POST to Shelly Cloud
2020-01-16 14:05:06 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-16 14:05:07 ERROR (Cloud) [pyShelly] Error update cloud, 'NoneType' object is not subscriptable
```

Simone

**Comment by chemelli74** [comment]
So far, 7 hours, I got 3 errors:

```
2020-01-16 14:05:06 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-16 16:41:46 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-16 18:12:43 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
```
Simone

**Comment by hakana** [comment]
Yes, I have reported this to Shelly, look like there is a problem with there API server

**Comment by chemelli74** [comment]
Hi, for your reference:

```
2020-01-17 16:18:07 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-17 18:17:43 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-17 21:36:48 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 04:20:08 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 09:32:26 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 11:39:29 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 15:35:29 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 15:57:41 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 17:52:01 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-18 19:05:02 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-19 00:19:18 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-19 00:24:37 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
2020-01-19 16:25:52 WARNING (Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'
```

Simone

**Comment by chemelli74** [comment]
Log clean after upgrading to 0.1.6b9.

Simone
