### ISSUE TITLE
Shelly bulb no white channel control

### ISSUE THREAD

**Issue by jacobhallgren** [StyraHem/ShellyForHASS#140]
Cannot control white channel from Homeassisant, 

Would be nice if you use this template: https://robert.stadsbygd.net/wp-content/uploads/2018/12/home-assistant-tv-led-strip.jpg

And not toggle to white with effect dropdown menu. This way in the link will also work correct for homekit.

**Comment by hakana** [comment]
I don't think this is how Shelly Bulb work, in the app you can't control white channel when in color mode?

**Comment by jacha05** [comment]
> I don't think this is how Shelly Bulb work, in the app you can't control white channel when in color mode?

You can't have them both on at the same time correct. But in HA if you use the slider white it should switch to white, and if you use the rgb it should switch to RGB

**Comment by hakana** [comment]
But then you cant choose color temperature? For me, it feels more confusing doing it that way. Please do a feature request and we will see later on.

**Comment by jacha05** [comment]
Yes you can look at the picture i linked to you have rgb control and white control. Now the white control is missing so you can only control the rgb from HA. Guess I have to go to MQTT

**Comment by hanimayahi** [comment]
I have this same problem, there should be a switch to change the bulb between RGB and White mode, like how it is done in the shelly web interface.

I had to make a MQTT script that changes the mode between rgb and white, but it's not a optimal solution.

**Comment by jacha05** [comment]
> 
> 
> I have this same problem, there should be a switch to change the bulb between RGB and White mode, like how it is done in the shelly web interface.
> 
> I had to make a MQTT script that changes the mode between rgb and white, but it's not a optimal solution.

Yeah its sad that the author does not care or understand this problem. Can you please share your mqtt code for this?

**Comment by hakana** [comment]
I understand the problem and also care ;), but right now there are other things that are more important right now.

**Comment by hakana** [comment]
Btw, you can do a http call to change this if you don't want to use MQTT.

https://shelly-api-docs.shelly.cloud/#shelly-bulb-settings

**Comment by jacobhallgren** [comment]
@hakana is this fixed now?

**Comment by hakana** [comment]
@jacobhallgren No it is not fixed, you can easily add a REST switch for changing the color state. I planning to add a switch for this but I need to focus more important issues first.

**Comment by david-kalbermatten** [comment]
@hakana I looked at how the LIFX integration does it. It seems they just disable the ability to set `white [255, 255, 255]` for the RGB-LEDs and instead use this to switch to white mode. This way you can either have the bulb change into white mode by changing the color temperature or by setting the color to white in the RGB-color wheel.
Personally, I find this the best solution since nobody really wants to use the mixed white color from the RGB LEDs.

**Comment by Nick3C** [comment]
I made this rest switch to do this...

- platform: rest
  name: "Shelly test"
  scan_interval: 5
  resource: http://192.168.0.(insert)/settings
  body_on: 'mode=color'
  body_off: 'mode=white'
  is_on_template: '{{ value_json.mode == "color"}}'
  headers:
    content-type: application/x-www-form-urlencoded
  username: (insert)
  password: (insert)

I plan to look into an automation to switch between the two mode based on colour brightness / colour levels.
