### ISSUE TITLE
0.1.7b1: log error

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#208]
Hi,

log shows this error quite often:

```
2020-03-04 14:43:18 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/shelly/device.py", line 93, in device_state_attributes
    for key, value in self._dev.block.info_values.items():
RuntimeError: dictionary changed size during iteration
```

Simone

**Comment by hakana** [comment]
Fixed in 0.1.7.b2

**Comment by chemelli74** [comment]
Confirmed fixed in b2

**Comment by jandrop** [comment]
Hi, for me this is still happening on version 0.1.8

![image](https://user-images.githubusercontent.com/8020875/83338722-67176700-a2c7-11ea-926f-96193e123d31.png)

**Comment by chemelli74** [comment]
Different issue.
You have to update your config, there is no more a generic “power”.

Always review release notes for all version to lean changes.

Simone

**Comment by jandrop** [comment]
> Different issue.
> You have to update your config, there is no more a generic “power”.
> 
> Always review release notes for all version to lean changes.
> 
> Simone

Omg, sorry for the confusion. I didn't realize that this was a different error.

**Comment by jandrop** [comment]
> Different issue.
> You have to update your config, there is no more a generic “power”.
> 
> Always review release notes for all version to lean changes.
> 
> Simone

BTW I've reviewed my config and I don´t know what do you mean with generic power, I don´t have any generic power on my config.

shelly:
  cloud_auth_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  cloud_server: "shelly-xxxxxxxxxxxxxxxxxxxxx"
  discovery: true
  igmp_fix: true
  host_ip: a.b.c.d
  additional_information: true
  power_decimals: 1
  scan_interval: 5
  sensors:
  - power
  - voltage
  devices:
  - id: b9f4fa
    name: Luz invitados
    light_switch: true
  - id: ba2066
    name: Luz salon
    light_switch: true
  - id: b9f486
    name: Luz cocina
    light_switch: true

**Comment by chemelli74** [comment]
what about that

```
sensors:
  - power
```

?

Simone

**Comment by jandrop** [comment]
> what about that
> 
> ```
> sensors:
>   - power
> ```
> 
> ?
> 
> Simone

Hi, this is in the documentation, 

![image](https://user-images.githubusercontent.com/8020875/83389094-e902af80-a3ef-11ea-86d8-b8cc26e15f90.png)

If I remove that my sensor disapears.
