### ISSUE TITLE
[BUG] Platform shelly does not generate unique IDs

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#307]
## Environment

- ShellyForHASS release with the issue: 0.1.9.b2
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.110.1
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

Log error logged, no functional issue so far

## Expected behavior

No error logged

## Traceback/Error logs

```txt
2020-05-23 16:11:13 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_ecfabcc576f5_firmware_update. Platform shelly does not generate unique IDs
```

**Comment by chemelli74** [comment]
Restarted the device and got one more log row:

```
2020-05-23 16:20:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 501, in async_remove
    await self.async_internal_will_remove_from_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/restore_state.py", line 255, in async_internal_will_remove_from_hass
    data.async_restore_entity_removed(self.entity_id)
  File "/usr/src/homeassistant/homeassistant/helpers/restore_state.py", line 207, in async_restore_entity_removed
    self.entity_ids.remove(entity_id)
KeyError: 'switch.shelly_shsw_1_ecfabcc576f5_firmware_update'
2020-05-23 16:21:15 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_ecfabcc576f5_firmware_update. Platform shelly does not generate unique IDs
```

Simone

**Comment by JSteunou** [comment]
I think I have the same issue 

https://www.facebook.com/groups/shellyforhass/permalink/582217759074445/

**Comment by JSteunou** [comment]
More log

```
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_e098068d928b. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_e098068d928b. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.binary_sensor] Entity id already exists - ignoring: binary_sensor.shelly_shsw_1_e098068d928b_switch. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.binary_sensor] Entity id already exists - ignoring: binary_sensor.shelly_shsw_1_e098068d928b_switch. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_e098068d04d1. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_e098068d04d1. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.binary_sensor] Entity id already exists - ignoring: binary_sensor.shelly_shsw_1_e098068d04d1_switch. Platform shelly does not generate unique IDs
2020-06-03 19:43:12 ERROR (MainThread) [homeassistant.components.binary_sensor] Entity id already exists - ignoring: binary_sensor.shelly_shsw_1_e098068d04d1_switch. Platform shelly does not generate unique IDs
2020-06-03 19:43:13 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shsw_1_e098068d04d1_uptime. Platform shelly does not generate unique IDs
2020-06-03 19:43:13 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shsw_1_e098068d04d1_uptime. Platform shelly does not generate unique IDs
2020-06-03 19:43:13 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shsw_1_e098068d928b_uptime. Platform shelly does not generate unique IDs
2020-06-03 19:43:13 ERROR (MainThread) [homeassistant.components.sensor] Entity id already exists - ignoring: sensor.shelly_shsw_1_e098068d928b_uptime. Platform shelly does not generate unique IDs
2020-06-03 19:44:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140462479491536] 'switch.shelly_shsw_1_e098068d928b'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 419, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shsw_1_e098068d928b'
2020-06-03 19:44:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140462479491536] 'switch.shelly_shsw_1_e098068d928b'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 419, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shsw_1_e098068d928b'
2020-06-03 19:45:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:46:34 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:46:38 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:47:12 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:47:51 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:47:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 19:49:03 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_boolean.lux
2020-06-03 20:05:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140462479491536] 'switch.shelly_shsw_1_e098068d928b'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 419, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shsw_1_e098068d928b'
2020-06-03 20:15:38 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[5]['state']. Got None
2020-06-03 20:28:01 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[5]['state']. Got None
2020-06-03 20:36:31 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[6]['state']. Got None
2020-06-03 21:58:11 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:19:21 WARNING (Thread-146) [pychromecast.socket_client] [SHIELD(192.168.1.24):8009] Heartbeat timeout, resetting connection
2020-06-03 22:19:51 ERROR (Thread-146) [pychromecast.socket_client] [SHIELD(192.168.1.24):8009] Failed to connect to service SHIELD-Android-TV-e4c13e77da0f1c009f190c994c96c720._googlecast._tcp.local., retrying in 5.0s
2020-06-03 22:30:13 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:38:14 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:43:14 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:43:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140462472531920] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-06-03 22:46:14 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:56:15 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 22:56:44 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[6]['state']. Got None
2020-06-03 22:57:15 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 23:06:26 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[6]['state']. Got None
2020-06-03 23:08:16 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 23:09:16 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
2020-06-03 23:10:16 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 237, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 135, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
```

Then it just goes on and on

**Comment by JSteunou** [comment]
Could it be related to last shelly firmware? There was an update I made before seeing this bug

**Comment by JSteunou** [comment]
Also I have a functional issue, related to this I think : from 2 shellys, only one is working as a switch, the duplicated one does not work anymore.

**Comment by JSteunou** [comment]
Ok I solve my issue, nothing to do with this one I am sorry. I still have the error about duplicate entry, but indeed there are no visible errors.

Mine was because going from yml to db it adds another Shelly integration. Having more than one integration trigger the websocket error logged above.

**Comment by chemelli74** [comment]
Seems fixed in latest 0.1.9.

Simone

**Comment by TracyP** [comment]
Not fixed for me.  Been having this for all recent releases.
